"""Verified Charlotte + Raleigh multifamily recruiting candidates."""

from datetime import date

MANUAL_CANDIDATES = [
    {"name": "Dean Smith", "company": "Newmark", "title": "Vice Chairman, Multifamily Capital Markets", "city": "Charlotte", "market": "Charlotte + Raleigh", "website": "https://www.nmrk.com/people/dean-smith", "source_url": "https://www.nmrk.com/people/dean-smith", "source_type": "manual_verified", "scraped_date": date.today().isoformat()},
    {"name": "John Heimburger", "company": "Newmark", "title": "Vice Chairman, Multifamily Capital Markets", "city": "Charlotte", "market": "Charlotte + Raleigh", "website": "https://www.nmrk.com/people/john-heimburger", "source_url": "https://www.nmrk.com/people/john-heimburger", "source_type": "manual_verified", "scraped_date": date.today().isoformat()},
    {"name": "Jason Kon", "company": "Newmark", "title": "Senior Managing Director, Multifamily Capital Markets", "city": "Charlotte", "market": "Charlotte + Raleigh", "website": "https://www.nmrk.com/people/jason-kon", "source_url": "https://www.nmrk.com/people/jason-kon", "source_type": "manual_verified", "scraped_date": date.today().isoformat()},
    {"name": "Sean Wood", "company": "Newmark", "title": "Vice Chairman, Multifamily Capital Markets", "city": "Raleigh-Durham", "market": "Charlotte + Raleigh", "website": "https://www.nmrk.com/people/sean-wood", "source_url": "https://www.nmrk.com/people/sean-wood", "source_type": "manual_verified", "scraped_date": date.today().isoformat()},
    {"name": "John Munroe", "company": "Newmark", "title": "Senior Managing Director, Multifamily Capital Markets", "city": "Raleigh-Durham", "market": "Charlotte + Raleigh", "website": "https://www.nmrk.com/people/john-munroe", "source_url": "https://www.nmrk.com/people/john-munroe", "source_type": "manual_verified", "scraped_date": date.today().isoformat()},

    {"name": "John Gavigan", "company": "JLL", "title": "Managing Director, Capital Markets", "city": "Charlotte", "market": "Charlotte + Raleigh", "website": "https://www.jll.com/en-us/people/bio-broker/john.gavigan", "source_url": "https://www.jll.com/en-us/people/bio-broker/john.gavigan", "source_type": "manual_verified", "scraped_date": date.today().isoformat()},
    {"name": "John Mikels", "company": "JLL", "title": "Managing Director, Capital Markets", "city": "Charlotte", "market": "Charlotte + Raleigh", "website": "https://www.jll.com/en-us/people/bio-broker/john.mikels", "source_url": "https://www.jll.com/en-us/people/bio-broker/john.mikels", "source_type": "manual_verified", "scraped_date": date.today().isoformat()},
    {"name": "Ben Bury", "company": "JLL", "title": "Senior Director, Capital Markets", "city": "Charlotte", "market": "Charlotte + Raleigh", "website": "https://www.jll.com/en-us/people/bio-broker/ben.bury", "source_url": "https://www.jll.com/en-us/people/bio-broker/ben.bury", "source_type": "manual_verified", "scraped_date": date.today().isoformat()},

    {"name": "Tai Cohen", "company": "CBRE", "title": "Vice Chairman", "city": "Carolinas", "market": "Charlotte + Raleigh", "website": "https://www.cbre.com/people/tai-cohen", "source_url": "https://www.cbre.com/people/tai-cohen", "source_type": "manual_verified", "scraped_date": date.today().isoformat()},
    {"name": "John Phoenix", "company": "CBRE", "title": "Vice Chairman", "city": "Charlotte", "market": "Charlotte + Raleigh", "website": "https://www.cbre.com/people/john-phoenix", "source_url": "https://www.cbre.com/people/john-phoenix", "source_type": "manual_verified", "scraped_date": date.today().isoformat()},
    {"name": "Kevin Kempf", "company": "CBRE", "title": "Executive Vice President", "city": "Charlotte", "market": "Charlotte + Raleigh", "website": "https://www.cbre.com/people/kevin-kempf", "source_url": "https://www.cbre.com/people/kevin-kempf", "source_type": "manual_verified", "scraped_date": date.today().isoformat()},
    {"name": "Richard Gore", "company": "CBRE", "title": "First Vice President", "city": "Carolinas", "market": "Charlotte + Raleigh", "website": "https://www.cbre.com/people/richard-gore-iii", "source_url": "https://www.cbre.com/people/richard-gore-iii", "source_type": "manual_verified", "scraped_date": date.today().isoformat()},
    {"name": "Louis Smart", "company": "CBRE", "title": "Senior Vice President", "city": "Carolinas", "market": "Charlotte + Raleigh", "website": "https://www.cbre.com/people/louis-smart", "source_url": "https://www.cbre.com/people/louis-smart", "source_type": "manual_verified", "scraped_date": date.today().isoformat()},

    {"name": "Michael Saclarides", "company": "Walker & Dunlop", "title": "Managing Director, Investment Sales", "city": "Charlotte", "market": "Charlotte + Raleigh", "website": "https://www.walkerdunlop.com/about/people/michael-saclarides", "source_url": "https://www.walkerdunlop.com/news/walker-dunlop-investment-sales-team-grows-north-carolina-platform-with-new-managing-director", "source_type": "manual_verified", "scraped_date": date.today().isoformat()},
    {"name": "Devin Bryan", "company": "Walker & Dunlop", "title": "Director, Investment Sales", "city": "Charlotte", "market": "Charlotte + Raleigh", "website": "https://www.walkerdunlop.com/about/people/devin-bryan", "source_url": "https://www.walkerdunlop.com/about/people/devin-bryan", "source_type": "manual_verified", "scraped_date": date.today().isoformat()},
    {"name": "Teddy Szyperski", "company": "Walker & Dunlop", "title": "Associate Director, Investment Sales", "city": "Charlotte", "market": "Charlotte + Raleigh", "website": "https://www.walkerdunlop.com/about/people/teddy-szyperski", "source_url": "https://www.walkerdunlop.com/about/people/teddy-szyperski", "source_type": "manual_verified", "scraped_date": date.today().isoformat()},
]
